class InvoicingPage {

    editInvoicing() {
        cy.get('#billing_first_name')
        .click()
        .clear()
        .type("Cláudio")
        cy.get('#billing_last_name')
        .click()
        .clear()
        .type("Santana")
        cy.get('#billing_company')
        .click()
        .clear()
        .type("EBAC")
        cy.get('#select2-billing_country-container')
        .click()
        .type("Brasil")
        .get('[aria-selected="true"]')
        .click()
        cy.get('#billing_address_1')
        .click()
        .clear()
        .type("Rua Fulano de Tal, 160")
        cy.get('#billing_address_2')
        .click()
        .clear()
        .type("Bloco 4, AP 202")
        cy.get('#billing_city')
        .click()
        .clear()
        .type("Araçatuba")
        cy.get('#select2-billing_state-container')
        .click()
        .type("São Paulo" + '{enter}')
        cy.get('#billing_postcode')
        .click()
        .clear()
        .type("16057-560")
        cy.get('#billing_phone')
        .click()
        .clear()
        .type("18912345678")
        cy.get('#billing_email')
        .click()
        .clear()
        .type("email@seuemail.com")
        cy.get('#order_comments')
        .click()
        .clear()
        .type("Entregar em um condomínio de esquina e de cor azul.")
        cy.get('#payment_method_cod').click()
        cy.get('.wc_payment_method.payment_method_cod > .payment_box > p').contains('Pagar em dinheiro na entrega.')
        cy.get('#terms').click()
    }
}

export default new InvoicingPage()
    


    

