name: ui-testing-cy

on:
  push:
    branches: [ exercicios/modulo-26 ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21.2.0'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          install-command: npm install
          browser: chrome
          start: npm test
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
